const SensitiveData = () => {
    return (
        <div>
            <div>This is my sensitive data 1</div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam et dolor sed ipsum eleifend volutpat nec a purus. Donec accumsan sagittis interdum. Etiam volutpat gravida maximus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque condimentum, est ac auctor varius, lorem dui dictum elit, ac vehicula ligula lorem sed magna. Nunc ornare porttitor augue, ac convallis libero. Quisque eget elit nisl. Nullam ac aliquet elit, vitae blandit eros. Etiam dapibus facilisis ante, ut dictum felis sagittis id. Vestibulum sagittis mattis aliquet. Mauris at neque sem. Quisque non orci ut lorem laoreet vehicula in et nibh.

Sed egestas felis ante, sit amet rutrum metus mattis at. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur sodales enim sit amet ex sollicitudin, eu interdum risus consequat. Sed a turpis pulvinar nisi facilisis scelerisque. Mauris blandit efficitur libero. Aliquam rutrum neque sed est porttitor dapibus. Curabitur cursus turpis in risus vehicula, eu iaculis dui feugiat. Vestibulum vitae risus pretium odio viverra iaculis ac ut purus. Etiam venenatis arcu non vulputate finibus. Phasellus vehicula massa eu urna ultricies fringilla. Etiam feugiat hendrerit tellus.

Nunc iaculis libero et dolor vehicula, ut maximus quam tristique. Duis euismod imperdiet ultricies. Sed dignissim lobortis rutrum. Etiam hendrerit lectus luctus, vulputate quam id, tempor risus. Curabitur condimentum maximus leo sit amet bibendum. Maecenas maximus libero sed justo luctus luctus. Vivamus ut augue eu dui sodales venenatis at nec felis. Nullam sit amet metus quis massa consequat pulvinar et vitae dui. Nullam et porta lacus.

Vivamus pharetra nisi urna, ac volutpat neque fringilla vitae. Nulla at mollis neque. Praesent rhoncus eu sem a varius. Curabitur posuere quis mauris nec pharetra. Etiam pretium diam augue, et porttitor ex elementum vitae. Nunc semper augue id dapibus varius. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis ut sem eu purus consectetur faucibus vitae et diam. Donec accumsan efficitur est, at hendrerit purus pulvinar vitae. Pellentesque posuere urna tempus, sagittis dui non, consequat turpis. Pellentesque vulputate eleifend pellentesque. Duis fringilla non neque non condimentum. Phasellus dignissim elementum neque at pellentesque. Proin ut imperdiet elit, eget rutrum urna. Vivamus eu diam sem. Morbi leo mi, vestibulum id augue quis, faucibus mattis massa.

Pellentesque ipsum nisl, egestas mattis tristique in, dapibus at nisl. Maecenas mollis nisl sit amet lacinia porttitor. Vestibulum aliquam vehicula hendrerit. Curabitur non tortor ac massa cursus iaculis. Nullam mattis et neque sit amet pellentesque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam vel ante lectus. Quisque in lacinia enim. Praesent ut dignissim purus. Ut vitae enim magna. Ut cursus varius tellus non eleifend.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam et dolor sed ipsum eleifend volutpat nec a purus. Donec accumsan sagittis interdum. Etiam volutpat gravida maximus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque condimentum, est ac auctor varius, lorem dui dictum elit, ac vehicula ligula lorem sed magna. Nunc ornare porttitor augue, ac convallis libero. Quisque eget elit nisl. Nullam ac aliquet elit, vitae blandit eros. Etiam dapibus facilisis ante, ut dictum felis sagittis id. Vestibulum sagittis mattis aliquet. Mauris at neque sem. Quisque non orci ut lorem laoreet vehicula in et nibh.

Sed egestas felis ante, sit amet rutrum metus mattis at. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur sodales enim sit amet ex sollicitudin, eu interdum risus consequat. Sed a turpis pulvinar nisi facilisis scelerisque. Mauris blandit efficitur libero. Aliquam rutrum neque sed est porttitor dapibus. Curabitur cursus turpis in risus vehicula, eu iaculis dui feugiat. Vestibulum vitae risus pretium odio viverra iaculis ac ut purus. Etiam venenatis arcu non vulputate finibus. Phasellus vehicula massa eu urna ultricies fringilla. Etiam feugiat hendrerit tellus.

Nunc iaculis libero et dolor vehicula, ut maximus quam tristique. Duis euismod imperdiet ultricies. Sed dignissim lobortis rutrum. Etiam hendrerit lectus luctus, vulputate quam id, tempor risus. Curabitur condimentum maximus leo sit amet bibendum. Maecenas maximus libero sed justo luctus luctus. Vivamus ut augue eu dui sodales venenatis at nec felis. Nullam sit amet metus quis massa consequat pulvinar et vitae dui. Nullam et porta lacus.

Vivamus pharetra nisi urna, ac volutpat neque fringilla vitae. Nulla at mollis neque. Praesent rhoncus eu sem a varius. Curabitur posuere quis mauris nec pharetra. Etiam pretium diam augue, et porttitor ex elementum vitae. Nunc semper augue id dapibus varius. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis ut sem eu purus consectetur faucibus vitae et diam. Donec accumsan efficitur est, at hendrerit purus pulvinar vitae. Pellentesque posuere urna tempus, sagittis dui non, consequat turpis. Pellentesque vulputate eleifend pellentesque. Duis fringilla non neque non condimentum. Phasellus dignissim elementum neque at pellentesque. Proin ut imperdiet elit, eget rutrum urna. Vivamus eu diam sem. Morbi leo mi, vestibulum id augue quis, faucibus mattis massa.

Pellentesque ipsum nisl, egestas mattis tristique in, dapibus at nisl. Maecenas mollis nisl sit amet lacinia porttitor. Vestibulum aliquam vehicula hendrerit. Curabitur non tortor ac massa cursus iaculis. Nullam mattis et neque sit amet pellentesque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam vel ante lectus. Quisque in lacinia enim. Praesent ut dignissim purus. Ut vitae enim magna. Ut cursus varius tellus non eleifend.
</p>
        </div>
    )
}

export default SensitiveData